# Generated by Django 5.2 on 2025-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('power', models.CharField(max_length=100)),
                ('cable_length', models.FloatField(max_length=40)),
                ('Warranty_period', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=100)),
                ('percent', models.IntegerField(default=0, max_length=100)),
                ('characteristic', models.ManyToManyField(to='products.characteristic')),
            ],
        ),
    ]
