# Generated by Django 5.2 on 2025-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='Warranty_period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
