# Generated by Django 5.2 on 2025-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='warranty_period',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
