# Generated by Django 5.2 on 2025-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristic',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.JSONField(default=dict),
        ),
    ]
